# Generated by Django 2.2.11 on 2020-04-01 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bisbo_files', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BisboFiles',
            new_name='BisboFile',
        ),
        migrations.CreateModel(
            name='UserDownloadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('bisbo_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_download', to='bisbo_files.BisboFile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_downloaded_files',
            },
        ),
    ]
